---
apiVersion: v2
name: rhtap-minio-operator
description: Helm Chart to manage the MinIO Operator for RHTAP
type: application
version: 1.3.0

dependencies:
  - name: operator
    version: 5.0.17
    condition: minIOOperator.enabled
