{{- if .Values.infrastructure.openShiftPipelines.enabled }}
  {{- $osp := .Values.infrastructure.openShiftPipelines -}}
  {{- if or
        $osp.patchClusterTektonConfig.annotations
        $osp.patchClusterTektonConfig.labels
  }}
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
  labels:
    {{- include "common.labels" . | nindent 4 }}
  namespace: {{ $osp.namespace }}
  name: {{ printf "patch-tekton-%s" $osp.name }}
spec:
  template:
    spec:
      serviceAccountName: {{ printf "patch-%s" $osp.name }}
      restartPolicy: Never
      initContainers:
        #
        # Copying the scripts that will be used on the subsequent containers, the
        # scripts are shared via the "/scripts" volume.
        #
    {{- include "common.copyScripts" . | nindent 8 }}
      containers:
    {{- if $osp.patchClusterTektonConfig.annotations }}
        #
        # Patch the Tekton Config with the provided annotations.
        #
        - name: patch-annotations
          image: registry.redhat.io/openshift4/ose-tools-rhel9
          env:
            - name: KIND
              value: tektonconfig
            - name: RESOURCE_NAME
              value: {{ $osp.patchClusterTektonConfig.resourceName }}
          command:
            - /scripts/oc-amend.sh
          args:
            - annotate
      {{- range $k, $v := $osp.patchClusterTektonConfig.annotations }}
            - {{ printf "%s=%s" $k $v | quote }}
      {{- end }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          securityContext:
            allowPrivilegeEscalation: false
    {{- end }}
    {{- if $osp.patchClusterTektonConfig.labels }}
        #
        # Patch the Tekton Config with the provided labels.
        #
        - name: patch-labels
          image: registry.redhat.io/openshift4/ose-tools-rhel9
          env:
            - name: KIND
              value: tektonconfig
            - name: RESOURCE_NAME
              value: {{ $osp.patchClusterTektonConfig.resourceName }}
          command:
            - /scripts/oc-amend.sh
          args:
            - label
     {{- range $k, $v := $osp.patchClusterTektonConfig.labels }}
            - {{ printf "%s=%s" $k $v | quote }}
     {{- end }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
          securityContext:
            allowPrivilegeEscalation: false
    {{- end }}
      volumes:
        - name: scripts
          emptyDir: {}
  {{- end }}
{{- end }}
