---
apiVersion: v2
name: tssc-integrations
description: TSSC Integrations
type: application
version: "1.7.0"
annotations:
  tssc.redhat-appstudio.github.com/depends-on: tssc-acs, tssc-gitops, tssc-dh
