---
name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/go

      #
      # TODO(otaviof): In order to build this container image, we need Red Hat
      #   container registry credentials.
      #
      # - name: Container Image
      #   uses: ./.github/actions/buildah
      #   with:
      #     tags: "latest,${{ github.ref }}"
      #     IMAGE_REPO_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make github-release
